name: Automated Preprocessing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preprocess-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_preprocess_data.py

      - name: Move processed data
        run: |
          mv sgtest.csv preprocessing/
          mv sgtrain.csv preprocessing/

      # - name: Commit processed data
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #   run: |
      #     git config --global user.name ${{ secrets.username }}
      #     git config --global user.email ${{ secrets.email }}
      #     git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
      #     git add preprocessing/sgtest.csv preprocessing/sgtrain.csv
      #     git commit -m 'Berhasil update dataset' || echo "Tidak Berhasil Mengunggah dataset terbaru"
      #     git push
